### ISSUE TITLE
Dark Mode — Can you create/offer this style option?

### ISSUE THREAD

**Issue by quicksite** [babyman/quick-tabs-chrome-extension#286]
I saw on the Quick Tabs OPTIONS page the CSS window, but I do not know how to create a CSS style. If anyone knows how to do this, could you pls copy the code here?  

I also looked for a STYLUS style at userstyles.org, but no results for Quick Tabs

**Comment by babyman** [comment]
@unglud put this together if you want to give it a try [DarkTheme](https://github.com/babyman/quick-tabs-chrome-extension/blob/master/3rdParty/css/darkTheme.css)

**Comment by quicksite** [comment]
I am so grateful for this reply. I just pasted it in, and works beautifully. Thanks very much!

**Comment by roko-p** [comment]
Here's another one:

```css
body{
  background:#101010
}
div.title {
  color: white;
}
div.url {
    color: #84acbf
}
.qs_input {
  background: #40494e;
  color: white;
}
div.separator.big {
  color: #b185ff;
}
.noresult {
    color: #ae97f7
}
img {
    background-color: #000000
}
.item {
    border-bottom: 1px solid rgb(255 255 255 / 12%)
}
```

**Comment by quicksite** [comment]
Thank you Evan, appreciate it.

**Comment by the-a-man-006** [comment]
Could anyone write an updated script for the same? Please please pretty please...

**Comment by caph1993** [comment]
I'm using this one, slightly more elaborated and with larger font, which I prefer:

```css
/* Quick Tabs — Dark Mode + Larger UI v7 */

body {
  width: 520px;
  font-size: 14px;
  background-color: #1c1c1e;
  color: #e2e2e5;
}

/* ── Search bar ── */
.qs_wrapper {
  background-color: #1c1c1e;
}

.qs_input {
  font-size: 15px;
  padding: 10px 8px;
  background-color: #2c2c2e;
  color: #e2e2e5;
  border-bottom: 2px solid #4285f4;
}

.qs_input::placeholder {
  color: #666;
}

/* ── Match highlight ──
   Normal rows:   soft blue on dark — visible without weight
   Hover rows:    warm gold on warm brown — stays readable
   Selected rows: bright gold on navy — high contrast, clearly distinct
                  from the surrounding blue-tinted text               */
b {
  font-weight: normal;
  text-decoration: none;
  color: #7eb8f7;
}

.item:hover b {
  color: #ffd166;
}

.withfocus b,
.withfocus:hover b {
  color: #ffd166;
}

/* ── Section separators ── */
div.separator.big {
  height: 36px;
  font-size: 11px;
  font-weight: 600;
  letter-spacing: 0.07em;
  text-transform: uppercase;
  color: #777;
  background: rgba(255, 255, 255, 0.03);
  border-top: 1px solid rgba(255, 255, 255, 0.07);
  border-bottom: 1px solid rgba(255, 255, 255, 0.07);
}

div.separator.big span {
  padding-top: 8px;
}

/* ── List items ── */
.item {
  height: 46px;
  padding-left: 3px;
  border-bottom: 1px solid rgba(255, 255, 255, 0.05);
}

.item > div:last-child {
  height: 100%;
  padding-left: 8px;
}

/* ── Favicon ── */
img {
  background-color: transparent;
  padding-top: 0;
}

div.tabimage img {
  padding: 5px 4px 4px 4px;
  margin: 6px 8px 0 8px;
}

div.hideicon {
  width: 4px;
  height: 35px;
}

/* ── Title & URL ── */
div.title {
  padding-top: 4px;
  font-size: 14px;
  color: #dde1e7;
}

div.url {
  font-size: 11px;
  color: #5a6070;
}

/* ── Closed tabs ── */
div.closed div.tabimage {
  opacity: 0.35;
}

div.closed div.title {
  color: #4a4f5a;
}

/* ── No results ── */
.noresult {
  font-size: 15px;
  color: #555;
}

/* ── Hover ── */
.item:hover,
.item:hover div.title,
div.closed.item:hover div.title,
.item:hover div.url {
  background-color: #2e2a24;
  color: #f0c080;
}

/* ── Selected/focused ── */
.withfocus,
.withfocus div.title,
div.closed.withfocus div.title,
.withfocus div.url,
.withfocus:hover,
.withfocus:hover div.title,
div.closed.withfocus:hover div.title,
.withfocus:hover div.url {
  background-color: #1e3a5a;
  color: #c8dcf5;
}

.withfocus,
.withfocus:hover {
  box-shadow: inset 3px 0 0 #4a90d9;
}

/* ── Close / remove button ── */
div.close, div.remove {
  width: 36px;
}

/* ── Scrollbar ── */
::-webkit-scrollbar {
  width: 4px;
  background-color: #1c1c1e;
}

::-webkit-scrollbar-thumb:vertical {
  background-color: #3a3a3a;
  border-radius: 4px;
  -webkit-border-image: none;
  border-width: 0;
  min-height: 20px;
}
```

Extra: a small divider that signals different window, copied from [this comment](https://github.com/babyman/quick-tabs-chrome-extension/issues/368#issuecomment-2470017363), (although, the items are not sorted by window, so it is not an ideal way to signal windoes, but I use it anyway)

```css

/* ── Window group dividers ── */
.tab.window-0:not(.window-0 ~ .window-0),
.tab.window-1:not(.window-1 ~ .window-1),
.tab.window-2:not(.window-2 ~ .window-2),
.tab.window-3:not(.window-3 ~ .window-3),
.tab.window-4:not(.window-4 ~ .window-4),
.tab.window-5:not(.window-5 ~ .window-5),
.tab.window-6:not(.window-6 ~ .window-6),
.tab.window-7:not(.window-7 ~ .window-7),
.tab.window-8:not(.window-8 ~ .window-8),
.tab.window-9:not(.window-9 ~ .window-9) {
  border-top: 2px solid #3a3f50;
}

#content-list > .item:first-child {
  border-top: none;
}
```

<img width="1915" height="1200" alt="Image" src="https://github.com/user-attachments/assets/576b1a45-49e5-40be-82a8-a9748e276d82" />
